package com.mygdx.game.mistfall.hero.cards.enums;

public enum HC_IdentifierEnum {

	HC_CROW_DAGGER,
	HC_CROW_HOODED_CLOAK,
	HC_CROW_UTILITY_BELT,
	HC_CROW_ACROBATIC_DODGE,
	HC_CROW_BACKSTAB,
	HC_CROW_DAGGER_THROW,
	HC_CROW_PREPARATION,
	HC_CROW_SHADOWSTEP,
	HC_CROW_VERSATILITY,
	HC_CROW_FORAGER,
	HC_CROW_DOUBLE_STAB,
	HC_CROW_LEAD_ASTRAY,
	HC_CROW_MISDIRECTION,
	HC_CROW_WASTE_NOT,
	HC_CROW_LOST_IN_THE_SHADOWS,
	HC_CROW_SHORT_BLADE_MASTERY,
	HC_CROW_CANNY_DIVERSION,
	HC_CROW_I_WALK_THROUGH_SHADOWS,
	HC_CROW_MASTERWORK_TOOLKIT,
	HC_CROW_VENOMTONGUE
}
